Repository atharvatechnology/Apex-app, pull requests merged in 2022-07, with the labels that each got.

#22 Register
  babel.config.js
  jsconfig.json
  package-lock.json
  src/components/elements/CustomButton/index.js
  src/components/elements/CustomTextInput/index.js
  src/components/modules/signin/Login.js
  src/components/modules/signup/Register.js
  src/data/Signin/login.js
  src/data/signup/register.js
  src/styles/_library.scss
  src/styles/elements/CustomButton.scss
  src/styles/modules/signin/login.scss
  src/styles/modules/signup/Register.scss
  src/utils/api.js
  src/utils/validation/index.js
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#24 VerifyNumber page created
  package-lock.json
  src/components/modules/ResetPassword/VerifyNumber.js
  src/components/modules/signin/Login.js
  src/components/templates/VerifyNumber.js
  src/data/Signin/login.js
  src/navigation/ResetPassword/Reset.js
  src/screens/ResetPassword/VerifyNumber.js
  src/styles/modules/ResetPassword/VerifyNumber.scss
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#28 home page scss corrected
  src/components/elements/CustomDropdown/index.js
  src/components/elements/Navbar/Navbar.js
  src/components/modules/Pages/Home.js
  src/components/modules/ResetPassword/Reset.js
  src/components/modules/signup/Interest.js
  src/components/modules/signup/Register.js
  src/components/templates/Home.js
  src/components/templates/Login.js
  src/navigation/AppNavigation.js
  src/navigation/Home/Home.js
  src/screens/Pages/Home.js
  src/screens/ResetPassword/VerifyNumber.js
  src/screens/Signin/Login.js
  src/styles/_common.scss
  src/styles/_library.scss
  src/styles/elements/CustomDropdown.scss
  src/styles/elements/NavBar/Navbar.scss
  src/styles/modules/Pages/CustomDropDown.scss
  src/styles/modules/Pages/Home.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#31 animation
  src/components/modules/walkthrough/walkthrough.js
Labels: :heavy_plus_sign: enhancement:fire:

#35 reduc and verify api
  package-lock.json
  package.json
  src/components/modules/Pages/Home.js
  src/components/modules/signin/Login.js
  src/components/modules/signup/Register.js
  src/components/modules/signup/Verify.js
  src/data/Signin/login.js
  src/data/signup/verify.js
  src/navigation/AppNavigation.js
  src/store/actionTypes.js
  src/store/actions/auth.js
  src/store/reducers/auth.js
  src/store/reducers/index.js
  src/store/store.js
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#36 Exam page
  src/assets/images/filter.png
  src/assets/images/search-interface-symbol.png
  src/components/elements/CustomButton/index.js
  src/components/elements/CustomTextInput/index.js
  src/components/elements/Navbar/Navbar.js
  src/components/modules/Pages/Exam.js
  src/components/templates/Exam.js
  src/navigation/AppNavigation.js
  src/navigation/Home/Exam.js
  src/screens/Pages/Exam.js
  src/screens/Pages/Home.js
  src/styles/_common.scss
  src/styles/modules/Pages/Exam.scss
Labels: :new:feature :partying_face:

#37 Home Page component completed
  src/assets/images/home.jpeg
  src/components/elements/CustomButton/index.js
  src/components/modules/Pages/Home.js
  src/navigation/AppNavigation.js
  src/styles/_common.scss
  src/styles/elements/NavBar/Navbar.scss
  src/styles/modules/Pages/CustomDropDown.scss
  src/styles/modules/Pages/Home.scss
  src/styles/modules/onBoarding.scss
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#38 Home page css updated
  src/components/modules/Pages/Exam.js
  src/components/modules/Pages/ExamPayment.js
  src/navigation/AppNavigation.js
  src/styles/elements/CustomButton.scss
  src/styles/modules/Pages/Home.scss
Labels: :heavy_plus_sign: enhancement:fire:

#43 filter popup
  src/assets/images/Filter.png
  src/assets/images/filter.png
  src/components/elements/CustomButtonPopup/index.js
  src/components/modules/Pages/Exam.js
  src/components/modules/Pages/ExamDetail.js
  src/components/templates/ExamDetail.js
  src/navigation/AppNavigation.js
  src/navigation/Home/ExamDetail.js
  src/screens/Pages/ExamDetail.js
  src/store/actions/auth.js
  src/styles/elements/CustomButton.scss
  src/styles/elements/CustomButtonPopup.scss
  src/styles/modules/Pages/ExamDetail.scss
Labels: :new:feature :partying_face:

#48 courseOverview page created
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Pages/ExamDetail.js
  src/components/templates/CourseOverview.js
  src/components/templates/Courses.js
  src/components/templates/Home.js
  src/navigation/AppNavigation.js
  src/navigation/Home/Courses.js
  src/screens/Pages/CourseOverview.js
  src/styles/modules/Pages/CourseOverview.scss
  src/styles/modules/Pages/Courses.scss
  src/styles/modules/Pages/ExamPayment.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#49 Backend home
  src/components/modules/Pages/Home.js
  src/store/actionTypes.js
  src/store/actions/home.js
  src/store/reducers/home.js
  src/store/reducers/index.js
Labels: :heavy_plus_sign: enhancement:fire:

#50 session popup
  src/components/elements/CustomButtonPopup/index.js
  src/components/elements/CustomSessionPopup/index.js
  src/components/modules/Pages/Exam.js
  src/components/modules/Pages/ExamDetail.js
  src/navigation/AppNavigation.js
  src/styles/elements/CustomButtonPopup.scss
  src/styles/elements/CustomSessionPopup.scss
Labels: :heavy_plus_sign: enhancement:fire:

#52 Home page Css corrected
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/Home.js
  src/components/templates/ExamPayment.js
  src/styles/modules/Pages/Home.scss
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:

#54 home page css corrected
  src/components/modules/Pages/Home.js
  src/styles/modules/Pages/Home.scss
Labels: :heavy_plus_sign: enhancement:fire:

#56 home page css corrected
  src/components/modules/Pages/Home.js
  src/styles/modules/Pages/Home.scss
Labels: :new:feature :partying_face:

#57 Exam page css corrected
  src/components/modules/Pages/CoursePayment.js
  src/components/modules/Pages/Exam.js
  src/components/templates/CoursePayment.js
  src/navigation/AppNavigation.js
  src/navigation/Home/CoursePayment.js
  src/navigation/Home/ExamDetail.js
  src/navigation/Home/ExamPayment.js
  src/screens/Pages/CoursePayment.js
  src/screens/Pages/Exam.js
  src/styles/modules/Pages/CoursePayment.scss
  src/styles/modules/Pages/Exam.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#61 Filter image is created in course page
  src/components/elements/CustomButtonPopup/index.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Pages/ExamDetail.js
  src/styles/modules/Pages/Courses.scss
Labels: :new:feature :partying_face:

#62 Profile page created
  src/assets/images/tulogo.png
  src/components/elements/CustomButton/index.js
  src/components/elements/CustomButtonPopup/index.js
  src/components/elements/CustomSessionPopup/index.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Pages/ExamPayment.js
  src/components/modules/Profile/Profile.js
  src/components/templates/Profile.js
  src/navigation/AppNavigation.js
  src/navigation/Profile/Profile.js
  src/screens/Profile/Profile.js
  src/styles/modules/Profile/Profile.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#63 profile page
  src/components/elements/CustomProfilePopup/index.js
  src/components/elements/CustomProfilePopup/index1.js
  src/components/modules/Profile/Profile.js
  src/navigation/AppNavigation.js
  src/styles/elements/CustomProfilePopup.scss
  src/styles/modules/Profile/Profile.scss
Labels: :heavy_plus_sign: enhancement:fire:

#67 Edit pop created in home
  src/components/elements/CustomProfilePopup/index.js
  src/components/elements/CustomProfilePopup/index1.js
  src/components/elements/CustomProfilePopup/index2.js
  src/components/elements/CustomSessionPopup/index1.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Profile/Profile.js
  src/navigation/AppNavigation.js
  src/styles/elements/CustomProfilePopup1.scss
  src/styles/modules/Pages/Courses.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#68 HeaderSeach component created
  src/components/elements/HeaderSearch/HeaderSearch.js
  src/components/elements/Navbar/Navbar.js
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Pages/Home.js
  src/styles/elements/HeaderSearch/HeaderSearch.scss
  src/styles/modules/Pages/Courses.scss
  src/styles/modules/Pages/Exam.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#69 enroll now session popup
  android/app/src/main/assets/fonts/OpenSans-ExtraBold.ttf
  android/app/src/main/assets/fonts/OpenSans-Regular.ttf
  ios/ApexMobile.xcodeproj/project.pbxproj
  ios/ApexMobile/Info.plist
  react-native.config.js
  src/assets/fonts/OpenSans-ExtraBold.ttf
  src/assets/fonts/OpenSans-Regular.ttf
  src/components/elements/CustomProfilePopup/index.js
  src/components/elements/CustomProfilePopup/index1.js
  src/components/elements/CustomSessionPopup/index.js
  src/components/modules/Profile/Profile.js
  src/navigation/AppNavigation.js
  src/navigation/BottomTabs/BottomTabs.js
  src/navigation/Course/CoursePayment.js
  src/navigation/Course/Courses.js
  src/navigation/Home/Courses.js
  src/navigation/Home/ExamDetail.js
  src/navigation/Home/Home.js
  src/navigation/Profile/Profile.js
  src/styles/_common.scss
  src/styles/_library.scss
  src/styles/elements/CustomProfilePopup.scss
  src/styles/elements/CustomSessionPopup.scss
  src/styles/modules/Profile/Profile.scss
Labels: :bug: bug, :heavy_plus_sign: enhancement:fire:

#70 props pass from courses page to headerseach page
  src/components/elements/HeaderSearch/HeaderSearch.js
  src/components/modules/Pages/Courses.js
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#72 making the HeaderSearch page dymanic
  src/components/elements/HeaderSearch/HeaderSearch.js
  src/components/modules/Pages/Courses.js
  src/styles/_library.scss
  src/styles/elements/HeaderSearch/HeaderSearch.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#73 development
  src/components/elements/CustomSessionPopup/index.js
  src/components/modules/Pages/ExamDetail.js
  src/components/modules/Pages/Home.js
  src/store/actionTypes.js
  src/store/actions/auth.js
  src/store/actions/exam.js
  src/store/actions/home.js
  src/store/reducers/exam.js
  src/store/reducers/index.js
  src/styles/_library.scss
  src/styles/modules/Pages/ExamDetail.scss
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:

#74 css
  android/app/src/main/assets/fonts/OpenSans-Bold.ttf
  android/app/src/main/assets/fonts/OpenSans-BoldItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-Italic.ttf
  android/app/src/main/assets/fonts/OpenSans-Light.ttf
  android/app/src/main/assets/fonts/OpenSans-LightItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-Medium.ttf
  android/app/src/main/assets/fonts/OpenSans-MediumItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-SemiBold.ttf
  android/app/src/main/assets/fonts/OpenSans-SemiBoldItalic.ttf
  assets/fonts/OpenSans-Bold.ttf
  assets/fonts/OpenSans-BoldItalic.ttf
  assets/fonts/OpenSans-ExtraBold.ttf
  assets/fonts/OpenSans-ExtraBoldItalic.ttf
  assets/fonts/OpenSans-Italic.ttf
  assets/fonts/OpenSans-Light.ttf
  assets/fonts/OpenSans-LightItalic.ttf
  assets/fonts/OpenSans-Medium.ttf
  assets/fonts/OpenSans-MediumItalic.ttf
  assets/fonts/OpenSans-Regular.ttf
  assets/fonts/OpenSans-SemiBold.ttf
  assets/fonts/OpenSans-SemiBoldItalic.ttf
  ios/ApexMobile.xcodeproj/project.pbxproj
  ios/ApexMobile/Info.plist
  src/assets/fonts/OpenSans-Bold.ttf
  src/assets/fonts/OpenSans-BoldItalic.ttf
  src/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  src/assets/fonts/OpenSans-Italic.ttf
  src/assets/fonts/OpenSans-Light.ttf
  src/assets/fonts/OpenSans-LightItalic.ttf
  src/assets/fonts/OpenSans-Medium.ttf
  src/assets/fonts/OpenSans-MediumItalic.ttf
  src/assets/fonts/OpenSans-SemiBold.ttf
  src/assets/fonts/OpenSans-SemiBoldItalic.ttf
  src/components/modules/Pages/Home.js
  src/styles/_common.scss
  src/styles/_library.scss
  src/styles/modules/Pages/Courses.scss
  src/styles/modules/Pages/Exam.scss
  src/styles/modules/Pages/ExamDetail.scss
  src/styles/modules/Pages/Home.scss
Labels: :heavy_plus_sign: enhancement:fire:

#75 development
  src/components/modules/Pages/ExamDetail.js
  src/styles/modules/Pages/Exam.scss
  src/utils/api.js
Labels: :heavy_plus_sign: enhancement:fire:

#76 css
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/ExamPayment.js
  src/styles/_common.scss
  src/styles/_library.scss
  src/styles/modules/Pages/ExamPayment.scss
Labels: :heavy_plus_sign: enhancement:fire:

#77 courses page dymanic
  src/components/elements/HeaderSearch/HeaderSearch.js
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/CoursePayment.js
  src/components/modules/Pages/ExamDetail.js
  src/components/modules/Pages/ExamPayment.js
  src/screens/Pages/CourseOverview.js
  src/styles/_library.scss
  src/styles/elements/HeaderSearch/HeaderSearch.scss
  src/styles/modules/Pages/CourseOverview.scss
  src/styles/modules/Pages/CoursePayment.scss
  src/styles/modules/Pages/ExamDetail.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#78 added font in course overview
  src/components/modules/Pages/CourseOverview.js
  src/styles/_library.scss
  src/styles/modules/Pages/CourseOverview.scss
Labels: :heavy_plus_sign: enhancement:fire:

#79 font
  src/components/elements/CustomButtonPopup/index1.js
  src/components/elements/CustomSessionPopup/index1.js
  src/components/elements/HeaderSearch/HeaderSearch.js
  src/components/elements/Navbar/Navbar.js
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/CoursePayment.js
  src/components/modules/Pages/Courses.js
  src/components/modules/Pages/ExamDetail.js
  src/components/modules/Pages/ExamPayment.js
  src/styles/_common.scss
  src/styles/_library.scss
  src/styles/elements/CustomButton.scss
  src/styles/elements/CustomButtonPopup1.scss
  src/styles/elements/CustomInput.scss
  src/styles/elements/CustomSessionPopup1.scss
  src/styles/elements/HeaderSearch/HeaderSearch.scss
  src/styles/elements/NavBar/Navbar.scss
  src/styles/modules/Pages/CoursePayment.scss
  src/styles/modules/Pages/Courses.scss
  src/styles/modules/Pages/ExamPayment.scss
Labels: :heavy_plus_sign: enhancement:fire:

#80 exam page
  src/components/elements/CustomButtonPopup/index.js
  src/components/elements/CustomProfilePopup/index2.js
  src/components/modules/Pages/Exam.js
  src/components/modules/Pages/ExamPayment.js
  src/styles/_common.scss
  src/styles/elements/CustomButtonPopup.scss
  src/styles/elements/CustomProfilePopup.scss
  src/styles/elements/CustomProfilePopup1.scss
  src/styles/modules/Pages/Exam.scss
Labels: :bug: bug

#82 font and css
  src/components/modules/Pages/CourseOverview.js
  src/components/modules/Pages/Exam.js
  src/components/modules/Pages/Home.js
  src/styles/_common.scss
  src/styles/modules/Pages/CourseOverview.scss
Labels: :heavy_plus_sign: enhancement:fire:

#83 Exams page created
  src/assets/images/MCQ.png
  src/components/modules/Exams/Exams.js
  src/components/templates/Exams.js
  src/navigation/AppNavigation.js
  src/navigation/Home/Home.js
  src/screens/Exams/Exams.js
  src/styles/_common.scss
  src/styles/elements/CustomButtonPopup.scss
  src/styles/modules/Exams/Exams.scss
Labels: :heavy_plus_sign: enhancement:fire:, :new:feature :partying_face:

#84 custom modal
  src/components/elements/CustomButton/index.js
  src/components/elements/CustomModalPopup/index.js
  src/styles/elements/CustomModal.scss
Labels: :heavy_plus_sign: enhancement:fire:
